language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
sudo: enabled
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master