language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
  - npm run build
deploy:
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master