language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
sudo: enabled
install:
- npm install
script:
- npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: bash prod-deploy.sh
    local_dir: build
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash stage-deploy.sh
    local_dir: build
    on:
      branch: dev
git:
  depth: 3
before_install:
- openssl aes-256-cbc -K $encrypted_496418eb094a_key -iv $encrypted_496418eb094a_iv
  -in deploy-keys.enc -out deploy-keys -d
